a32test: ViKeySample.c
	clear
	gcc  -c ViKeySample.c 
	gcc  -o ta32 ViKeySample.o ViKey.X86.a

s32test: ViKeySample.c
	clear
	gcc  -c ViKeySample.c 
	gcc  -o ts32 ViKeySample.o ViKey.X86.so

a64test: ViKeySample.c
	clear
	gcc  -c ViKeySample.c 
	gcc  -o ta64 ViKeySample.o ViKey.X64.a

s64test: ViKeySample.c
	clear
	gcc  -c ViKeySample.c 
	gcc  -o ts64 ViKeySample.o ViKey.X64.so

